##The website title
name: HunterDavis.com
##Markdown processor
markdown: kramdown
##syntax highlighter. change it to pygments
highlighter: pygments

##define base_url for valid usage in sitemap.xml and robots.txt
base_url: http://www.hunterdavis.com
url: http://www.hunterdavis.com
sass:
  sass_dir: _sass
  style: :compressed
paginate: 5
paginate_path: "page:num"
##The website description (to be used in meta tags)
description: The personal blog of Hunter G. Davis
##Some frequently used keywords on your website
keywords: computer, science, hacker, javascript, emulator, gaming, leadership

##define this for disqus comment support
disqus: www.hunterdavis.com

##set this to enable google analytics
ga_id: UA-498331-1
#ga_domain: analyticsDomain

##Some commonly used links
links:
  email: hunterdavis@hey.com
  github: huntergdavis

##put desired image in img/ directory and set the value accordingly. If not defined, a placeholder image will be used.
about_image: placeholder.png
##comment this if you want full width posts with no sidebar
sidebar: on

plugins: [jekyll-paginate]
